/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Guest;

import Staff.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Database.DatabaseConnection; 
import java.awt.Insets;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeojvaldez
 */
public class guestBoatList extends javax.swing.JInternalFrame {

    /**
     * Creates new form staffReservation
     */
    public guestBoatList() {
        initComponents();
        removeBackground();
        DatabaseConnection();
        
        
 
    }
    
    Connection con; 
    PreparedStatement pst;
    ResultSet rs; 
    
    public final void DatabaseConnection() {
          String url = "jdbc:mysql://localhost:3306/beachResortManagement";
        String user = "root"; // MySQL username
        String password = ""; // MySQL password
        
        // Establishing the connection
        try {
            // Load MySQL JDBC driver (optional in newer versions of JDBC)
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Create the connection
            con = DriverManager.getConnection(url, user, password);
            
            System.out.println("Connected to the database successfully!");

            // Perform database operations here...

      
        } catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found: " + e.getMessage());
        }
    }
    
    public final void removeBackground(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UI = (BasicInternalFrameUI) this.getUI();
        UI.setNorthPane(null); 
    }
    
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoatDetails = new rojerusan.RSTableMetro();
        jTextField1 = new javax.swing.JTextField();
        rSComboMetro1 = new rojerusan.RSComboMetro();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBoatDetails.setBackground(new java.awt.Color(242, 242, 242));
        tblBoatDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblBoatDetails.setForeground(new java.awt.Color(255, 255, 255));
        tblBoatDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Boat Number", "Registration Date", "Name", "Details", "Capacity", "Price/Tour"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBoatDetails.setColorBackgoundHead(new java.awt.Color(39, 114, 160));
        tblBoatDetails.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblBoatDetails.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tblBoatDetails.setColorFilasBackgound2(new java.awt.Color(242, 242, 242));
        tblBoatDetails.setColorFilasForeground1(new java.awt.Color(27, 59, 95));
        tblBoatDetails.setColorFilasForeground2(new java.awt.Color(27, 59, 95));
        tblBoatDetails.setColorSelBackgound(new java.awt.Color(39, 114, 160));
        tblBoatDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        tblBoatDetails.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblBoatDetails.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblBoatDetails.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblBoatDetails.setGridColor(new java.awt.Color(255, 255, 255));
        tblBoatDetails.setRowHeight(30);
        tblBoatDetails.setSelectionBackground(new java.awt.Color(39, 114, 160));
        tblBoatDetails.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblBoatDetails.setShowGrid(false);
        tblBoatDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoatDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoatDetails);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1120, 570));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Seach here...");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 270, 40));

        rSComboMetro1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Number", "Name", "Capacity", "Price", "", "" }));
        rSComboMetro1.setColorArrow(new java.awt.Color(27, 59, 95));
        rSComboMetro1.setColorBorde(new java.awt.Color(39, 114, 160));
        rSComboMetro1.setColorFondo(new java.awt.Color(39, 114, 160));
        rSComboMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSComboMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jPanel6.setBackground(new java.awt.Color(51, 204, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View Reservation");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBoatDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoatDetailsMouseClicked

    }//GEN-LAST:event_tblBoatDetailsMouseClicked

    private void rSComboMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSComboMetro1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new roomReservation().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private rojerusan.RSComboMetro rSComboMetro1;
    private rojerusan.RSTableMetro tblBoatDetails;
    // End of variables declaration//GEN-END:variables
}
