/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Guest;

import Staff.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Database.DatabaseConnection; 
import java.awt.Insets;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeojvaldez
 */
public class guestMainHome extends javax.swing.JInternalFrame {

    /**
     * Creates new form staffReservation
     */
    public guestMainHome() {
        initComponents();
        removeBackground();
        DatabaseConnection();
   
        
 
    }
    
    Connection con; 
    PreparedStatement pst;
    ResultSet rs; 
    
    public final void DatabaseConnection() {
          String url = "jdbc:mysql://localhost:3306/beachResortManagement";
        String user = "root"; // MySQL username
        String password = ""; // MySQL password
        
        // Establishing the connection
        try {
            // Load MySQL JDBC driver (optional in newer versions of JDBC)
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Create the connection
            con = DriverManager.getConnection(url, user, password);
            
            System.out.println("Connected to the database successfully!");

            // Perform database operations here...

      
        } catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found: " + e.getMessage());
        }
    }
    
    public final void removeBackground(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UI = (BasicInternalFrameUI) this.getUI();
        UI.setNorthPane(null); 
    }
    
   
    
   

    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new javax.swing.JPanel();
        txtHead = new javax.swing.JLabel();
        pnlReserveRoom = new javax.swing.JPanel();
        pnlAvailableRoom1 = new javax.swing.JPanel();
        pnlAvailableRoom2 = new javax.swing.JPanel();
        pnlAvailableRoom3 = new javax.swing.JPanel();
        pnlReserveRoom1 = new javax.swing.JPanel();
        pnlReserveRoom2 = new javax.swing.JPanel();
        pnlReserveRoom3 = new javax.swing.JPanel();
        pnlAvailableRoom4 = new javax.swing.JPanel();
        pnlAvailableRoom5 = new javax.swing.JPanel();
        pnlAvailableRoom6 = new javax.swing.JPanel();
        pnlReserveRoom5 = new javax.swing.JPanel();
        pnlReserveRoom4 = new javax.swing.JPanel();
        pnlAvailableRoom7 = new javax.swing.JPanel();
        pnlAvailableRoom8 = new javax.swing.JPanel();
        pnlReserveRoom6 = new javax.swing.JPanel();
        pnlReserveRoom7 = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlmain.setBackground(new java.awt.Color(242, 242, 242));
        pnlmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHead.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtHead.setForeground(new java.awt.Color(0, 0, 0));
        txtHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHead.setText("Featurering Rooms and Boats");
        txtHead.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(39, 114, 160)));
        pnlmain.add(txtHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1140, 80));

        pnlReserveRoom.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlReserveRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 270, 190));

        pnlAvailableRoom1.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlAvailableRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 270, 190));

        pnlAvailableRoom2.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlAvailableRoom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, 190));

        pnlAvailableRoom3.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlAvailableRoom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 270, 190));

        pnlReserveRoom1.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlReserveRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 270, 190));

        pnlReserveRoom2.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlReserveRoom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 270, 190));

        pnlReserveRoom3.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlReserveRoom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 270, 190));

        pnlAvailableRoom4.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlAvailableRoom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 270, 190));

        pnlAvailableRoom5.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAvailableRoom6.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlAvailableRoom5.add(pnlAvailableRoom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 270, 190));

        pnlReserveRoom5.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlAvailableRoom5.add(pnlReserveRoom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 270, 190));

        pnlmain.add(pnlAvailableRoom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 270, 190));

        pnlReserveRoom4.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlReserveRoom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 270, 190));

        pnlAvailableRoom7.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAvailableRoom8.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlAvailableRoom7.add(pnlAvailableRoom8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 270, 190));

        pnlReserveRoom6.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlAvailableRoom7.add(pnlReserveRoom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 270, 190));

        pnlmain.add(pnlAvailableRoom7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 270, 190));

        pnlReserveRoom7.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlmain.add(pnlReserveRoom7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, 270, 190));

        getContentPane().add(pnlmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlAvailableRoom1;
    private javax.swing.JPanel pnlAvailableRoom2;
    private javax.swing.JPanel pnlAvailableRoom3;
    private javax.swing.JPanel pnlAvailableRoom4;
    private javax.swing.JPanel pnlAvailableRoom5;
    private javax.swing.JPanel pnlAvailableRoom6;
    private javax.swing.JPanel pnlAvailableRoom7;
    private javax.swing.JPanel pnlAvailableRoom8;
    private javax.swing.JPanel pnlReserveRoom;
    private javax.swing.JPanel pnlReserveRoom1;
    private javax.swing.JPanel pnlReserveRoom2;
    private javax.swing.JPanel pnlReserveRoom3;
    private javax.swing.JPanel pnlReserveRoom4;
    private javax.swing.JPanel pnlReserveRoom5;
    private javax.swing.JPanel pnlReserveRoom6;
    private javax.swing.JPanel pnlReserveRoom7;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JLabel txtHead;
    // End of variables declaration//GEN-END:variables
}
