/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guest;

import Staff.*;
import Admin.*;
import Staff.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeojvaldez
 */
public class guestMakeReservation extends javax.swing.JFrame {
    
    int value = 0;
    /**
     * Creates new form roomAdd
     */
    public guestMakeReservation() {
        initComponents();
        DatabaseConnection();
        populateRoomNumbersComboBox();
        
        
    }
    
    Connection con; 
    PreparedStatement pst;
    ResultSet rs; 
    
    public final void DatabaseConnection() {
        String url = "jdbc:mysql://localhost:3306/beachResortManagement";
        String user = "root"; // MySQL username
        String password = ""; // MySQL password
        
        // Establishing the connection
        try {
            // Load MySQL JDBC driver (optional in newer versions of JDBC)
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Create the connection
            con = DriverManager.getConnection(url, user, password);
            
            System.out.println("Connected to the database successfully!");

            // Perform database operations here...

      
        } catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found: " + e.getMessage());
        }
    }
    
    
    
    private void populateRoomNumbersComboBox() {
        // Clear the combo box before adding items
        cmbRoomNumber.removeAllItems();

        // Add the default entry (null or a placeholder)
        cmbRoomNumber.addItem("Select a Room Number");

        try {
            // SQL query to fetch all room numbers from the room table
            String sql = "SELECT room_number FROM room";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Populate combo box with room numbers
            while (rs.next()) {
                String roomNumber = rs.getString("room_number");
                cmbRoomNumber.addItem(roomNumber); // Add each room number to the combo box
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error fetching room numbers: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        AdultNumber = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        checkInDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtphone1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        cmbRoomNumber = new rojerusan.RSComboMetro();
        jLabel17 = new javax.swing.JLabel();
        rSComboMetro2 = new rojerusan.RSComboMetro();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rSComboMetro3 = new rojerusan.RSComboMetro();
        jPanel5 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        txtErrorMessage = new javax.swing.JLabel();
        checkOutDate = new com.toedter.calendar.JDateChooser();
        txtErrorMessage1 = new javax.swing.JLabel();
        txtvalue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(27, 59, 95)));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Boat Tour");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, -1));

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Check-In");
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, -1));

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Check-Out");
        panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 110, -1));

        jLabel12.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Chldren");
        panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, -1));
        panel.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, 30));

        AdultNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AdultNumberStateChanged(evt);
            }
        });
        panel.add(AdultNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 30));

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Adult");
        panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, -1));

        checkInDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                checkInDatePropertyChange(evt);
            }
        });
        panel.add(checkInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 160, 30));

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Room Number");
        panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, -1));

        txtphone1.setBackground(new java.awt.Color(255, 255, 255));
        txtphone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panel.add(txtphone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 330, 30));

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Time");
        panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 110, -1));

        jLabel16.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Unavailable Date");
        panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 100, -1));

        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        panel.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 80, -1));

        jRadioButton2.setText("No");
        panel.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 330, 10));
        panel.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 70, 30));

        cmbRoomNumber.setColorArrow(new java.awt.Color(27, 59, 95));
        cmbRoomNumber.setColorBorde(new java.awt.Color(39, 114, 160));
        cmbRoomNumber.setColorFondo(new java.awt.Color(39, 114, 160));
        cmbRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomNumberActionPerformed(evt);
            }
        });
        cmbRoomNumber.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbRoomNumberPropertyChange(evt);
            }
        });
        panel.add(cmbRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 220, 30));

        jLabel17.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Date");
        panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        rSComboMetro2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        rSComboMetro2.setColorArrow(new java.awt.Color(27, 59, 95));
        rSComboMetro2.setColorBorde(new java.awt.Color(39, 114, 160));
        rSComboMetro2.setColorFondo(new java.awt.Color(39, 114, 160));
        rSComboMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro2ActionPerformed(evt);
            }
        });
        panel.add(rSComboMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 80, 30));

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Contact #:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 10));

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Address:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, -1));

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Reservation #:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));

        jLabel26.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("ENTRANCE");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, -1));

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, -1));

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Boat Ride Pice:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, -1));

        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Adult:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, -1));

        jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("00.00");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 110, -1));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Name:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, -1));

        jLabel32.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Total Room Price:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        jLabel33.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("00.00");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, -1));

        jLabel34.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("00.00");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, -1));

        jLabel35.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("00.00");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 110, -1));

        jLabel37.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("00.00");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, -1));

        jLabel36.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("Children:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, -1));

        jLabel38.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("00.00");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 110, -1));

        jLabel40.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Total:");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 340, 310));

        jPanel4.setBackground(new java.awt.Color(51, 204, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Show");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 5, 90, 20));

        panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 100, 30));

        jLabel18.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Room Number");
        panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, -1));

        rSComboMetro3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Date" }));
        rSComboMetro3.setColorArrow(new java.awt.Color(27, 59, 95));
        rSComboMetro3.setColorBorde(new java.awt.Color(39, 114, 160));
        rSComboMetro3.setColorFondo(new java.awt.Color(39, 114, 160));
        rSComboMetro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro3ActionPerformed(evt);
            }
        });
        panel.add(rSComboMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 160, 30));

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Cancel");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 70, 20));

        panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 90, 30));

        jPanel6.setBackground(new java.awt.Color(27, 59, 95));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Confirm");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 70, 20));

        panel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 90, 30));

        txtErrorMessage.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        txtErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErrorMessage.setText("(error message)");
        panel.add(txtErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 10));

        checkOutDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                checkOutDatePropertyChange(evt);
            }
        });
        panel.add(checkOutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, 30));

        txtErrorMessage1.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        txtErrorMessage1.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErrorMessage1.setText("(error message)");
        panel.add(txtErrorMessage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, 10));

        txtvalue.setText("jLabel4");
        panel.add(txtvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 820, 440));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Room & Boat Tour Reservation");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 770, 60));
        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
private int counter = 0;
    private void cmbRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomNumberActionPerformed
        txtErrorMessage1.setText(""); 
        txtErrorMessage.setText("");
        checkInDate.setDate(null);
        checkOutDate.setDate(null);
        counter = 0;
        
        
    }//GEN-LAST:event_cmbRoomNumberActionPerformed

    private void rSComboMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSComboMetro2ActionPerformed

    private void rSComboMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSComboMetro3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
  
                 new guestRoomUnavailableDate().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void checkInDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkInDatePropertyChange
    txtErrorMessage.setText("");                             
    // Only proceed if the date property changed
    if (!"date".equals(evt.getPropertyName())) {
        return;
    }

    // Get the selected check-in date
    java.util.Date checkInUtilDate = checkInDate.getDate();
    if (checkInUtilDate == null) {
       
        return;
    }

    // Get selected room number
    String roomNumber = (String) cmbRoomNumber.getSelectedItem(); 
    if (roomNumber == null || roomNumber.isEmpty() || "Select a Room Number".equals(roomNumber)) {
        txtErrorMessage.setText("Select a room number");
        return;
    }

    // Convert to SQL date
    java.sql.Date sqlCheckIn = new java.sql.Date(checkInUtilDate.getTime());

    try {
        // Query to check room availability on the check-in date
        String query = "SELECT COUNT(*) FROM room_reservation WHERE room_number = ? " +
                      "AND ? BETWEEN check_in_date AND check_out_date";
        
        pst = con.prepareStatement(query);
        pst.setString(1, roomNumber);
        pst.setDate(2, sqlCheckIn);
        
        rs = pst.executeQuery();
        if (rs.next()) {
            int count = rs.getInt(1);
            if (count > 0) {
                txtErrorMessage.setText("Room #" + roomNumber + " not available on " + 
                    new SimpleDateFormat("MMM dd, yyyy").format(checkInUtilDate));
                txtErrorMessage.setForeground(Color.RED);
            } 
        }
    } catch (SQLException ex) {
        txtErrorMessage.setText("Error checking room availability");
        System.err.println("Database error: " + ex.getMessage());
    } 

    }//GEN-LAST:event_checkInDatePropertyChange

    
    private void checkOutDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkOutDatePropertyChange
        txtErrorMessage1.setText(""); 
        if (!"date".equals(evt.getPropertyName())) {
        return;
    }
        

    // Get selected dates
    java.util.Date checkInUtilDate = checkInDate.getDate();
    java.util.Date checkOutUtilDate = checkOutDate.getDate();
    
    // Validate check-in date is selected
    if (checkInUtilDate == null && counter > 1) {
        
        txtErrorMessage1.setText("Select a check-in date first");
        txtErrorMessage1.setForeground(Color.RED);
        return;
    } else {
        counter++;
    }
    
    // Validate check-out date is selected
    if (checkOutUtilDate == null) {
        return;
    }
    
    // Get selected room number
    String roomNumber = (String) cmbRoomNumber.getSelectedItem(); 
    if (roomNumber == null || roomNumber.isEmpty() || roomNumber.equals("Select a Room Number")) {
        txtErrorMessage1.setText("Select a room number");
        txtErrorMessage1.setForeground(Color.RED);
        return;
    }

    // Validate check-out is after check-in
    if (checkOutUtilDate.before(checkInUtilDate)) {
        txtErrorMessage1.setText("Check-out must be after check-in");
        txtErrorMessage1.setForeground(Color.RED);
        return;
    }

    // Convert to SQL dates
    java.sql.Date sqlCheckIn = new java.sql.Date(checkInUtilDate.getTime());
    java.sql.Date sqlCheckOut = new java.sql.Date(checkOutUtilDate.getTime());

    try {
        // Query to check for conflicting reservations
        String query = "SELECT COUNT(*) FROM room_reservation WHERE room_number = ? " +
                     "AND ((check_in_date <= ? AND check_out_date >= ?) OR " +  // New dates within existing
                     "(check_in_date BETWEEN ? AND ?) OR " +                   // Existing starts during new
                     "(check_out_date BETWEEN ? AND ?))";                      // Existing ends during new
        
        pst = con.prepareStatement(query);
        pst.setString(1, roomNumber);
        pst.setDate(2, sqlCheckOut);  // Note parameter order matches query
        pst.setDate(3, sqlCheckIn);
        pst.setDate(4, sqlCheckIn);
        pst.setDate(5, sqlCheckOut);
        pst.setDate(6, sqlCheckIn);
        pst.setDate(7, sqlCheckOut);
        
        rs = pst.executeQuery();
        if (rs.next()) {
            int count = rs.getInt(1);
            if (count > 0) {
                txtErrorMessage1.setText("Room not available for selected dates");
                txtErrorMessage1.setForeground(Color.RED);
            } 
        }
    } catch (SQLException ex) {
        txtErrorMessage1.setText("Error checking availability");
        System.err.println("Database error: " + ex.getMessage());
    } 

      
    }//GEN-LAST:event_checkOutDatePropertyChange

    private void cmbRoomNumberPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbRoomNumberPropertyChange
       txtErrorMessage1.setText(""); 
        txtErrorMessage.setText(""); 
        
    }//GEN-LAST:event_cmbRoomNumberPropertyChange

    private void AdultNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AdultNumberStateChanged
       
         int value = (Integer) AdultNumber.getValue();
        txtvalue.setText(String.valueOf(value)); 
    }//GEN-LAST:event_AdultNumberStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guestMakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guestMakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guestMakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guestMakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guestMakeReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AdultNumber;
    private com.toedter.calendar.JDateChooser checkInDate;
    private com.toedter.calendar.JDateChooser checkOutDate;
    private rojerusan.RSComboMetro cmbRoomNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JPanel panel;
    private rojerusan.RSComboMetro rSComboMetro2;
    private rojerusan.RSComboMetro rSComboMetro3;
    private javax.swing.JLabel txtErrorMessage;
    private javax.swing.JLabel txtErrorMessage1;
    private javax.swing.JTextField txtphone1;
    private javax.swing.JLabel txtvalue;
    // End of variables declaration//GEN-END:variables
}
