/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guest;

import Admin.*;
import Staff.*;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeojvaldez
 */
public class guestReservation extends javax.swing.JFrame {

    private int userId;
    
    public guestReservation(int userId) {
        this.userId = userId;
        initComponents();
        DatabaseConnection();
        showPendingRoomReservations();
        showCompleteRoomReservations();
    }
    
    Connection con; 
    PreparedStatement pst;
    ResultSet rs; 
    
    public final void DatabaseConnection() {
          String url = "jdbc:mysql://localhost:3306/beachResortManagement";
        String user = "root"; // MySQL username
        String password = ""; // MySQL password
        
        // Establishing the connection
        try {
            // Load MySQL JDBC driver (optional in newer versions of JDBC)
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Create the connection
            con = DriverManager.getConnection(url, user, password);
            
            System.out.println("Connected to the database successfully!");

            // Perform database operations here...

      
        } catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found: " + e.getMessage());
        }
    }
    
    public final void showPendingRoomReservations() {
    // Ensure that the database connection is valid
   if (con == null) {
    System.out.println("Database connection is not established.");
    return;
}

String query = "SELECT reservation_number, check_in_date, check_out_date FROM reservation WHERE status = 'Pending' AND user_id = ?";

// Get the table model
DefaultTableModel reservationModel = (DefaultTableModel) tblRoomReservationPending.getModel();
reservationModel.setRowCount(0); // Clear old data

try (PreparedStatement pst = con.prepareStatement(query)) {

    // Set the user ID parameter (replace with your actual user ID variable)
    pst.setInt(1, userId); // Example: if userId = "GUEST123"

    try (ResultSet rs = pst.executeQuery()) {
        while (rs.next()) {
            String reservationNumber = rs.getString("reservation_number");
            Date checkInDate = rs.getDate("check_in_date");
            Date checkOutDate = rs.getDate("check_out_date");

            reservationModel.addRow(new Object[]{reservationNumber, checkInDate, checkOutDate});
        }
    }

} catch (SQLException e) {
    System.out.println("Error retrieving data: " + e.getMessage());
}

}
    
    public final void showCompleteRoomReservations() {
    // Ensure that the database connection is valid
   if (con == null) {
    System.out.println("Database connection is not established.");
    return;
}

String query = "SELECT reservation_number, check_in_date, check_out_date FROM reservation WHERE status = 'Check-out' AND user_id = ?";

// Get the table model
DefaultTableModel reservationModel = (DefaultTableModel) tblRoomReservationComplete.getModel();
reservationModel.setRowCount(0); // Clear old data

try (PreparedStatement pst = con.prepareStatement(query)) {

    // Set the user ID parameter (replace with your actual user ID variable)
    pst.setInt(1, userId); // Example: if userId = "GUEST123"

    try (ResultSet rs = pst.executeQuery()) {
        while (rs.next()) {
            String reservationNumber = rs.getString("reservation_number");
            Date checkInDate = rs.getDate("check_in_date");
            Date checkOutDate = rs.getDate("check_out_date");

            reservationModel.addRow(new Object[]{reservationNumber, checkInDate, checkOutDate});
        }
    }

} catch (SQLException e) {
    System.out.println("Error retrieving data: " + e.getMessage());
}

}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        materialTabbed1 = new GUI.MaterialTabbed();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRoomReservationPending = new rojerusan.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRoomReservationComplete = new rojerusan.RSTableMetro();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 114, 160), 7));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(27, 59, 95)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materialTabbed1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRoomReservationPending.setBackground(new java.awt.Color(242, 242, 242));
        tblRoomReservationPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation Number", "Check-in Date", "Check-out Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRoomReservationPending.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        tblRoomReservationPending.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblRoomReservationPending.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tblRoomReservationPending.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblRoomReservationPending.setColorFilasForeground1(new java.awt.Color(27, 59, 95));
        tblRoomReservationPending.setColorFilasForeground2(new java.awt.Color(27, 59, 95));
        tblRoomReservationPending.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tblRoomReservationPending.setColorSelBackgound(new java.awt.Color(39, 114, 160));
        tblRoomReservationPending.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        tblRoomReservationPending.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblRoomReservationPending.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblRoomReservationPending.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblRoomReservationPending.setGridColor(new java.awt.Color(204, 204, 204));
        tblRoomReservationPending.setRowHeight(30);
        tblRoomReservationPending.setSelectionBackground(new java.awt.Color(61, 58, 87));
        tblRoomReservationPending.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblRoomReservationPending.setShowGrid(false);
        tblRoomReservationPending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoomReservationPendingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRoomReservationPending);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 320));

        materialTabbed1.addTab("Pending", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRoomReservationComplete.setBackground(new java.awt.Color(242, 242, 242));
        tblRoomReservationComplete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation Number", "Check-in Date", "Check-out Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRoomReservationComplete.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        tblRoomReservationComplete.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblRoomReservationComplete.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tblRoomReservationComplete.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblRoomReservationComplete.setColorFilasForeground1(new java.awt.Color(27, 59, 95));
        tblRoomReservationComplete.setColorFilasForeground2(new java.awt.Color(27, 59, 95));
        tblRoomReservationComplete.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tblRoomReservationComplete.setColorSelBackgound(new java.awt.Color(39, 114, 160));
        tblRoomReservationComplete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        tblRoomReservationComplete.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblRoomReservationComplete.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblRoomReservationComplete.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblRoomReservationComplete.setGridColor(new java.awt.Color(204, 204, 204));
        tblRoomReservationComplete.setRowHeight(30);
        tblRoomReservationComplete.setSelectionBackground(new java.awt.Color(61, 58, 87));
        tblRoomReservationComplete.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblRoomReservationComplete.setShowGrid(false);
        tblRoomReservationComplete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoomReservationCompleteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblRoomReservationComplete);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 320));

        materialTabbed1.addTab("History", jPanel4);

        jPanel2.add(materialTabbed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 560, 390));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 560, 390));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("My Reservation");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 500, 60));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblRoomReservationPendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoomReservationPendingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRoomReservationPendingMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tblRoomReservationCompleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoomReservationCompleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRoomReservationCompleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guestReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guestReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guestReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guestReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int userId = 0;
                new guestReservation(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private GUI.MaterialTabbed materialTabbed1;
    private rojerusan.RSTableMetro tblRoomReservationComplete;
    private rojerusan.RSTableMetro tblRoomReservationPending;
    // End of variables declaration//GEN-END:variables
}
