/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Staff;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Database.DatabaseConnection; 
import java.awt.Insets;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeojvaldez
 */
public class staffMainHome extends javax.swing.JInternalFrame {

    /**
     * Creates new form staffReservation
     */
    public staffMainHome() {
        initComponents();
        removeBackground();
        DatabaseConnection();
   
        
 
    }
    
    Connection con; 
    PreparedStatement pst;
    ResultSet rs; 
    
    public final void DatabaseConnection() {
          String url = "jdbc:mysql://localhost:3306/beachResortManagement";
        String user = "root"; // MySQL username
        String password = ""; // MySQL password
        
        // Establishing the connection
        try {
            // Load MySQL JDBC driver (optional in newer versions of JDBC)
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Create the connection
            con = DriverManager.getConnection(url, user, password);
            
            System.out.println("Connected to the database successfully!");

            // Perform database operations here...

      
        } catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found: " + e.getMessage());
        }
    }
    
    public final void removeBackground(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UI = (BasicInternalFrameUI) this.getUI();
        UI.setNorthPane(null); 
    }
    
   
    
   

    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new javax.swing.JPanel();
        txtHead = new javax.swing.JLabel();
        pnlCheckin = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlWaterActivities = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlReserveRoom = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlConfirmReservation = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlAvailableRoom = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlAvailableBoat = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlReserveBoat = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlCancelReservation = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pnlGuest = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbooking1 = new rojerusan.RSTableMetro();
        jLabel24 = new javax.swing.JLabel();
        pnlUpcomming = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbooking = new rojerusan.RSTableMetro();
        jLabel23 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlmain.setBackground(new java.awt.Color(242, 242, 242));
        pnlmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHead.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtHead.setForeground(new java.awt.Color(0, 0, 0));
        txtHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHead.setText("Beach-Front Resort Managemenr System");
        txtHead.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(39, 114, 160)));
        pnlmain.add(txtHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1140, 80));

        pnlCheckin.setBackground(new java.awt.Color(255, 255, 255));
        pnlCheckin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        pnlCheckin.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("00");
        pnlCheckin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Check-in Today");
        pnlCheckin.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        pnlmain.add(pnlCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 270, 70));

        pnlWaterActivities.setBackground(new java.awt.Color(255, 255, 255));
        pnlWaterActivities.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 153, 51));
        pnlWaterActivities.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Water Activities");
        pnlWaterActivities.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("00");
        pnlWaterActivities.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        pnlmain.add(pnlWaterActivities, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 270, 70));

        pnlReserveRoom.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveRoom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(51, 204, 0));
        pnlReserveRoom.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Reserve Room");
        pnlReserveRoom.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 20));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("00");
        pnlReserveRoom.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        pnlmain.add(pnlReserveRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 270, 70));

        pnlConfirmReservation.setBackground(new java.awt.Color(255, 255, 255));
        pnlConfirmReservation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(0, 51, 204));
        pnlConfirmReservation.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("00");
        pnlConfirmReservation.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Confirm Reservation");
        pnlConfirmReservation.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        pnlmain.add(pnlConfirmReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 270, 70));

        pnlAvailableRoom.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableRoom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(204, 0, 51));
        pnlAvailableRoom.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Available Room");
        pnlAvailableRoom.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("00");
        pnlAvailableRoom.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        pnlmain.add(pnlAvailableRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 270, 70));

        pnlAvailableBoat.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvailableBoat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(204, 204, 0));
        pnlAvailableBoat.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("00");
        pnlAvailableBoat.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Available Boat");
        pnlAvailableBoat.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        pnlmain.add(pnlAvailableBoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 70));

        pnlReserveBoat.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserveBoat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(0, 204, 204));
        pnlReserveBoat.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("00");
        pnlReserveBoat.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Reserve Boat");
        pnlReserveBoat.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        pnlmain.add(pnlReserveBoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 270, 70));

        pnlCancelReservation.setBackground(new java.awt.Color(255, 255, 255));
        pnlCancelReservation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel28.setBackground(new java.awt.Color(204, 0, 204));
        pnlCancelReservation.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Cancel Reservation");
        pnlCancelReservation.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("00");
        pnlCancelReservation.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        pnlmain.add(pnlCancelReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 270, 70));

        pnlGuest.setBackground(new java.awt.Color(255, 255, 255));
        pnlGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblbooking1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Guest Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbooking1.setToolTipText("");
        tblbooking1.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        tblbooking1.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblbooking1.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tblbooking1.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblbooking1.setColorFilasForeground1(new java.awt.Color(27, 59, 95));
        tblbooking1.setColorFilasForeground2(new java.awt.Color(27, 59, 95));
        tblbooking1.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tblbooking1.setColorSelBackgound(new java.awt.Color(27, 59, 95));
        tblbooking1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        tblbooking1.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblbooking1.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblbooking1.setGridColor(new java.awt.Color(204, 204, 204));
        tblbooking1.setRowHeight(30);
        tblbooking1.setSelectionBackground(new java.awt.Color(27, 59, 95));
        tblbooking1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblbooking1.setShowGrid(false);
        tblbooking1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbooking1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbooking1);

        pnlGuest.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 380));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Currently Check-in");
        pnlGuest.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, 30));

        pnlmain.add(pnlGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 270, 460));

        pnlUpcomming.setBackground(new java.awt.Color(255, 255, 255));
        pnlUpcomming.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblbooking.setBackground(new java.awt.Color(242, 242, 242));
        tblbooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reservation ID", "Customer Name", "Room Number", "Check-in", "Check-out"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbooking.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        tblbooking.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblbooking.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tblbooking.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblbooking.setColorFilasForeground1(new java.awt.Color(27, 59, 95));
        tblbooking.setColorFilasForeground2(new java.awt.Color(27, 59, 95));
        tblbooking.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tblbooking.setColorSelBackgound(new java.awt.Color(27, 59, 95));
        tblbooking.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        tblbooking.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblbooking.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblbooking.setGridColor(new java.awt.Color(204, 204, 204));
        tblbooking.setRowHeight(30);
        tblbooking.setSelectionBackground(new java.awt.Color(27, 59, 95));
        tblbooking.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblbooking.setShowGrid(false);
        tblbooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbooking);

        pnlUpcomming.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 810, 380));

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Upcomming Check-In");
        pnlUpcomming.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, 30));

        pnlmain.add(pnlUpcomming, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 850, 460));

        getContentPane().add(pnlmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblbooking1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbooking1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblbooking1MouseClicked

    private void tblbookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbookingMouseClicked

    }//GEN-LAST:event_tblbookingMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlAvailableBoat;
    private javax.swing.JPanel pnlAvailableRoom;
    private javax.swing.JPanel pnlCancelReservation;
    private javax.swing.JPanel pnlCheckin;
    private javax.swing.JPanel pnlConfirmReservation;
    private javax.swing.JPanel pnlGuest;
    private javax.swing.JPanel pnlReserveBoat;
    private javax.swing.JPanel pnlReserveRoom;
    private javax.swing.JPanel pnlUpcomming;
    private javax.swing.JPanel pnlWaterActivities;
    private javax.swing.JPanel pnlmain;
    private rojerusan.RSTableMetro tblbooking;
    private rojerusan.RSTableMetro tblbooking1;
    private javax.swing.JLabel txtHead;
    // End of variables declaration//GEN-END:variables
}
