/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Admin;

import Staff.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Database.DatabaseConnection; 
import java.awt.Insets;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeojvaldez
 */
public class adminUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form staffReservation
     */
    public adminUsers() {
        initComponents();
        removeBackground();
        DatabaseConnection();
        showUserDetails();
       
        
 
    }
    
    Connection con; 
    PreparedStatement pst;
    ResultSet rs; 
    
    public final void DatabaseConnection() {
          String url = "jdbc:mysql://localhost:3306/beachResortManagement";
        String user = "root"; // MySQL username
        String password = ""; // MySQL password
        
        // Establishing the connection
        try {
            // Load MySQL JDBC driver (optional in newer versions of JDBC)
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Create the connection
            con = DriverManager.getConnection(url, user, password);
            
            System.out.println("Connected to the database successfully!");

            // Perform database operations here...

      
        } catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found: " + e.getMessage());
        }
    }
    
    public final void removeBackground(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UI = (BasicInternalFrameUI) this.getUI();
        UI.setNorthPane(null); 
    }
    
    public final void showUserDetails() {
    // Ensure that the database connection is valid
    if (con == null) {
        System.out.println("Database connection is not established.");
        return;
    }

    // Prepare the SQL query to fetch the required data from user_details table
    String query = "SELECT user_id, role, full_name, username, phone, address, email, password FROM user_details";
    
    // Set up the table model to display the data in the JTable
    DefaultTableModel userModel = (DefaultTableModel) tblUserDetails.getModel();
    
    // Clear any previous rows from the table
    userModel.setRowCount(0);

    // Use try-with-resources to automatically close the resources
    try (PreparedStatement pst = con.prepareStatement(query);
         ResultSet rs = pst.executeQuery()) {

        // Iterate over the result set and add data to the table
        while (rs.next()) {
            // Fetch each column's data
            int userId = rs.getInt("user_id");
            String role = rs.getString("role");
            String fullName = rs.getString("full_name");
            String username = rs.getString("username");
            String phone = rs.getString("phone");
            String address = rs.getString("address");
            String email = rs.getString("email");
            String password = rs.getString("password");
            

            // Add data to the table model
            userModel.addRow(new Object[] { userId, role, fullName, username, phone, address, email, password});
        }
    } catch (SQLException e) {
        System.out.println("Error connecting to the database: " + e.getMessage());
    }
}

    
    
   

    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserDetails = new rojerusan.RSTableMetro();
        txtsearch = new javax.swing.JTextField();
        rSComboMetro1 = new rojerusan.RSComboMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 740));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUserDetails.setBackground(new java.awt.Color(242, 242, 242));
        tblUserDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblUserDetails.setForeground(new java.awt.Color(255, 255, 255));
        tblUserDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Role", "Full Name", "Username", "Phone", "Address", "Email", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUserDetails.setColorBackgoundHead(new java.awt.Color(39, 114, 160));
        tblUserDetails.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblUserDetails.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tblUserDetails.setColorFilasBackgound2(new java.awt.Color(242, 242, 242));
        tblUserDetails.setColorFilasForeground1(new java.awt.Color(27, 59, 95));
        tblUserDetails.setColorFilasForeground2(new java.awt.Color(27, 59, 95));
        tblUserDetails.setColorSelBackgound(new java.awt.Color(39, 114, 160));
        tblUserDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        tblUserDetails.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblUserDetails.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblUserDetails.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblUserDetails.setGridColor(new java.awt.Color(255, 255, 255));
        tblUserDetails.setRowHeight(30);
        tblUserDetails.setSelectionBackground(new java.awt.Color(39, 114, 160));
        tblUserDetails.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblUserDetails.setShowGrid(false);
        tblUserDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUserDetails);
        if (tblUserDetails.getColumnModel().getColumnCount() > 0) {
            tblUserDetails.getColumnModel().getColumn(0).setResizable(false);
            tblUserDetails.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblUserDetails.getColumnModel().getColumn(1).setResizable(false);
            tblUserDetails.getColumnModel().getColumn(2).setResizable(false);
            tblUserDetails.getColumnModel().getColumn(4).setResizable(false);
            tblUserDetails.getColumnModel().getColumn(5).setResizable(false);
            tblUserDetails.getColumnModel().getColumn(6).setResizable(false);
            tblUserDetails.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1120, 570));

        txtsearch.setBackground(new java.awt.Color(255, 255, 255));
        txtsearch.setForeground(new java.awt.Color(102, 102, 102));
        txtsearch.setText("Seach here...");
        txtsearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtsearch.setBounds(new java.awt.Rectangle(0, 5, 0, 0));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        jPanel2.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 270, 40));

        rSComboMetro1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Room Number", "Type", "Occupancy", "Price", " ", " " }));
        rSComboMetro1.setColorArrow(new java.awt.Color(27, 59, 95));
        rSComboMetro1.setColorBorde(new java.awt.Color(39, 114, 160));
        rSComboMetro1.setColorFondo(new java.awt.Color(39, 114, 160));
        rSComboMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSComboMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1160, 660));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(39, 114, 160)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("List of Users");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update Details");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 110, 30));

        jPanel5.setBackground(new java.awt.Color(27, 59, 95));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add New Users");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 110, 30));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Delete Users");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 100, 30));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 110, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 820));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUserDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserDetailsMouseClicked

    }//GEN-LAST:event_tblUserDetailsMouseClicked

    private void rSComboMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSComboMetro1ActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new adminAddUser().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         new adminUpdateUser().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       
        new adminDeleteUser().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSComboMetro rSComboMetro1;
    private rojerusan.RSTableMetro tblUserDetails;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
