/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Staff.*;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author yeojvaldez
 */
public class adminUpdateUser extends javax.swing.JFrame {

    /**
     * Creates new form roomAdd
     */
    public adminUpdateUser() {
        initComponents();
        DatabaseConnection();
        populateUserIdsComboBox();
    }
    
    java.sql.Connection con; 
    PreparedStatement pst;
    ResultSet rs; 
    
    public final void DatabaseConnection() {
        String url = "jdbc:mysql://localhost:3307/beachResortManagement";
        String user = "root"; // MySQL username
        String password = ""; // MySQL password
        
        // Establishing the connection
        try {
            // Load MySQL JDBC driver (optional in newer versions of JDBC)
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Create the connection
            con = DriverManager.getConnection(url, user, password);
            
            System.out.println("Connected to the database successfully!");

            // Perform database operations here...

      
        } catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found: " + e.getMessage());
        }
    }
     
    public void populateUserIdsComboBox() {
    
        try {
        // Clear existing items
            cmbUserIds.removeAllItems();

            // Add default option
            cmbUserIds.addItem("Select User ID");

            // Get user IDs from database
            String sql = "SELECT user_id FROM user_details ORDER BY user_id";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Add each user ID to the combo box
            while (rs.next()) {
            cmbUserIds.addItem(rs.getString("user_id"));
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(adminUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover2 = new rojeru_san.complementos.RSButtonHover();
        txtFirstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbRole = new GUI.ComboBoxSuggestion();
        txtConfirmPassword = new javax.swing.JPasswordField();
        cmbUserIds = new GUI.ComboBoxSuggestion();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 114, 160), 7));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(27, 59, 95)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FIRST NAME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 30));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ROLE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, 30));

        rSButtonHover1.setBackground(new java.awt.Color(255, 0, 0));
        rSButtonHover1.setText("CANCEL");
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, -1));

        rSButtonHover2.setBackground(new java.awt.Color(0, 204, 0));
        rSButtonHover2.setText("UPDATE");
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 170, -1));

        txtFirstName.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName.setForeground(new java.awt.Color(102, 102, 102));
        txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 170, 30));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("LAST NAME");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, 30));

        txtLastName.setBackground(new java.awt.Color(255, 255, 255));
        txtLastName.setForeground(new java.awt.Color(102, 102, 102));
        txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 30));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 170, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("EMAIL");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 90, 30));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("PASSWORD");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 90, 30));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("PHONE");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, 30));

        txtPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtPhone.setForeground(new java.awt.Color(102, 102, 102));
        txtPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 170, 30));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("USER ID");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 30));

        cmbRole.setEditable(false);
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Staff", "Guest" }));
        cmbRole.setSelectedIndex(-1);
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        jPanel2.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, -1));

        txtConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirmPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 170, 30));

        cmbUserIds.setEditable(false);
        cmbUserIds.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Staff", "Guest" }));
        cmbUserIds.setSelectedIndex(-1);
        cmbUserIds.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUserIdsItemStateChanged(evt);
            }
        });
        cmbUserIds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserIdsActionPerformed(evt);
            }
        });
        jPanel2.add(cmbUserIds, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 470, 440));

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update User Details");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 480, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
       
   try {
    String userId = (String) cmbUserIds.getSelectedItem(); // Combo box for user ID
    String role = (String) cmbRole.getSelectedItem();
    String firstName = txtFirstName.getText().trim();
    String lastName = txtLastName.getText().trim();
    String phone = txtPhone.getText().trim();
    String email = txtEmail.getText().trim();
    String password = new String(txtConfirmPassword.getPassword()).trim();

    // Validate required fields
    if (userId == null || role == null || firstName.isEmpty() || lastName.isEmpty() ||
            phone.isEmpty() || email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate phone format
    if (!phone.matches("^\\d{10,15}$")) {
        JOptionPane.showMessageDialog(this, "Invalid phone number format (10-15 digits required)!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate email format
    if (!email.matches("^[\\w-.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        JOptionPane.showMessageDialog(this, "Invalid email format!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Combine first and last name
    String fullName = firstName + " " + lastName;

    // Hash password (placeholder)
   String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());

    PreparedStatement pst;

    // Check for duplicate email (excluding current user)
    String checkSql = "SELECT email FROM user_details WHERE email = ? AND user_id != ?";
    pst = con.prepareStatement(checkSql);
    pst.setString(1, email);
    pst.setString(2, userId);
    ResultSet rs = pst.executeQuery();
    if (rs.next()) {
        JOptionPane.showMessageDialog(this, "Email already registered to another user!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Update user info
    String updateSql = "UPDATE user_details SET role = ?, full_name = ?, phone = ?, email = ?, password = ? WHERE user_id = ?";
    pst = con.prepareStatement(updateSql);
    pst.setString(1, role);
    pst.setString(2, fullName);
    pst.setString(3, phone);
    pst.setString(4, email);
    pst.setString(5, hashedPassword);
    pst.setString(6, userId);

    int rowsAffected = pst.executeUpdate();
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "User updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }
} catch (SQLException ex) {
    java.util.logging.Logger.getLogger(adminUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}

  


    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void cmbUserIdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserIdsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUserIdsActionPerformed

    private void cmbUserIdsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUserIdsItemStateChanged
        try {
            String userId = (String) cmbUserIds.getSelectedItem();
            
// If no room number is selected (empty or null), do nothing
if (userId == null || userId.equals("Select User ID")) {
   
    return;
}

String sql = "SELECT role, full_name, phone, email FROM user_details WHERE user_id = ?";
pst = con.prepareStatement(sql);
pst.setString(1, userId);
rs = pst.executeQuery();

if (rs.next()) {
    try {
        // Set role, phone, and email directly
        cmbRole.setSelectedItem(rs.getString("role"));
        txtPhone.setText(rs.getString("phone"));
        txtEmail.setText(rs.getString("email"));
        
        // Split full name into first and last name
        String fullName = rs.getString("full_name").trim();
        String[] nameParts = fullName.split("\\s+", 2); // Split on first space only
        
        // Set first name (all text before last space)
        if (nameParts.length > 0) {
            txtFirstName.setText(nameParts[0]);
        } else {
            txtLastName.setText("");
        }
        
        // Set last name (remaining text after first space)
        if (nameParts.length > 1) {
            txtLastName.setText(nameParts[1]);
        } else {
            txtLastName.setText("");
        }
        txtConfirmPassword.setText("password"); 
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(adminUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
} else {
    
    JOptionPane.showMessageDialog(this, "User not found!", "Error", JOptionPane.WARNING_MESSAGE);
}
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(adminUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_cmbUserIdsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminUpdateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.ComboBoxSuggestion cmbRole;
    private GUI.ComboBoxSuggestion cmbUserIds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover2;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
