/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author yeojvaldez
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlsignout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtemail1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtemail3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtpass1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlsignout.setBackground(new java.awt.Color(255, 255, 255));
        pnlsignout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 59, 95), 15));
        pnlsignout.setPreferredSize(new java.awt.Dimension(550, 670));
        pnlsignout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sign Out");
        pnlsignout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 149, -1));

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel5.setText("Have already an account?");
        pnlsignout.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 160, -1));

        rSButtonHover1.setText("CREATE");
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        pnlsignout.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 130, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jLabel7.setText("Sign In");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        pnlsignout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 50, 20));

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel8.setText("Username");
        pnlsignout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, -1));
        pnlsignout.add(txtemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 330, 40));

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel9.setText("Password");
        pnlsignout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 110, -1));
        pnlsignout.add(txtemail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 330, 40));

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel10.setText("Email");
        pnlsignout.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, -1));

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        pnlsignout.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 330, 40));

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel11.setText("Confirm Password");
        pnlsignout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 110, -1));

        txtpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpass1ActionPerformed(evt);
            }
        });
        pnlsignout.add(txtpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 330, 40));

        getContentPane().add(pnlsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlsignout;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtemail3;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtpass1;
    // End of variables declaration//GEN-END:variables
}
