/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author yeojvaldez
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlsignout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textField1 = new textfield.TextField();
        textField2 = new textfield.TextField();
        textField3 = new textfield.TextField();
        textField4 = new textfield.TextField();
        textField5 = new textfield.TextField();
        passwordField1 = new textfield.PasswordField();
        passwordField2 = new textfield.PasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlsignout.setBackground(new java.awt.Color(255, 255, 255));
        pnlsignout.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        pnlsignout.setPreferredSize(new java.awt.Dimension(550, 670));
        pnlsignout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Create your Account");
        pnlsignout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 240, -1));

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Have already an account?");
        pnlsignout.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 160, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sign In");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        pnlsignout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 50, 20));

        textField1.setBackground(new java.awt.Color(255, 255, 255));
        textField1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        textField1.setLabelText("Last Name");
        pnlsignout.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 160, 45));

        textField2.setBackground(new java.awt.Color(255, 255, 255));
        textField2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        textField2.setLabelText("Email");
        pnlsignout.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 330, 45));

        textField3.setBackground(new java.awt.Color(255, 255, 255));
        textField3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        textField3.setLabelText("First Name");
        pnlsignout.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, 45));

        textField4.setBackground(new java.awt.Color(255, 255, 255));
        textField4.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        textField4.setLabelText("Phone");
        pnlsignout.add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 330, 45));

        textField5.setBackground(new java.awt.Color(255, 255, 255));
        textField5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        textField5.setLabelText("Address");
        pnlsignout.add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 330, 45));

        passwordField1.setBackground(new java.awt.Color(255, 255, 255));
        passwordField1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        passwordField1.setLabelText("Password");
        pnlsignout.add(passwordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 330, 45));

        passwordField2.setBackground(new java.awt.Color(255, 255, 255));
        passwordField2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        passwordField2.setLabelText("Confirm Password");
        passwordField2.setShowAndHide(true);
        passwordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField2ActionPerformed(evt);
            }
        });
        pnlsignout.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 330, 45));

        jPanel1.setBackground(new java.awt.Color(39, 114, 160));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 5, -1, 30));

        pnlsignout.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 140, 40));

        getContentPane().add(pnlsignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

    }//GEN-LAST:event_jLabel7MouseClicked

    private void passwordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private textfield.PasswordField passwordField1;
    private textfield.PasswordField passwordField2;
    private javax.swing.JPanel pnlsignout;
    private textfield.TextField textField1;
    private textfield.TextField textField2;
    private textfield.TextField textField3;
    private textfield.TextField textField4;
    private textfield.TextField textField5;
    // End of variables declaration//GEN-END:variables
}
