/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Staff.*;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author yeojvaldez
 */
public class adminUpdateBoat extends javax.swing.JFrame {

     
    File f = null;
    String path = null;
    private ImageIcon format = null;
    String fname = null;
    int s = 0;
    byte[] pimage = null;
    
    
    public adminUpdateBoat() {
        initComponents();
        DatabaseConnection();
        populateBoatNumbersComboBox();
    }
    
    java.sql.Connection con; 
    PreparedStatement pst;
    ResultSet rs; 
    
    public final void DatabaseConnection() {
          String url = "jdbc:mysql://localhost:3306/beachResortManagement";
        String user = "root"; // MySQL username
        String password = ""; // MySQL password
        
        // Establishing the connection
        try {
            // Load MySQL JDBC driver (optional in newer versions of JDBC)
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Create the connection
            con = DriverManager.getConnection(url, user, password);
            
            System.out.println("Connected to the database successfully!");

            // Perform database operations here...

      
        } catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found: " + e.getMessage());
        }
    }
    
    private void populateBoatNumbersComboBox() {
        // Clear the combo box before adding items
       cmbBoatNumbers.removeAllItems();

    // Add the default entry (null or a placeholder)
        cmbBoatNumbers.addItem("Select a Boat Number");

        try {
            // SQL query to fetch all boat numbers from the boat table
            String sql = "SELECT boat_number FROM boat";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Populate combo box with boat numbers
            while (rs.next()) {
                String boatNumber = rs.getString("boat_number");
                cmbBoatNumbers.addItem(boatNumber); // Add each boat number to the combo box
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error fetching boat numbers: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
private void loadBoatImage(byte[] imageData) {
    try {
        if (imageData == null || imageData.length == 0) {
            labelImage.setIcon(null);
            return;
        }

        ImageIcon originalIcon = new ImageIcon(imageData);
        Image scaledImage = originalIcon.getImage()
            .getScaledInstance(labelImage.getWidth(), 
                            labelImage.getHeight(), 
                            Image.SCALE_SMOOTH);
        labelImage.setIcon(new ImageIcon(scaledImage));
    } catch (Exception e) {
        labelImage.setIcon(null);
        System.err.println("Error loading image: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBoatName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        spinnerCapacity = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTourPrice = new javax.swing.JTextField();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover2 = new rojeru_san.complementos.RSButtonHover();
        timePickerButton1 = new com.raven.swing.TimePickerButton();
        jPanel3 = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        cmbBoatNumbers = new GUI.ComboBoxSuggestion();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 114, 160), 7));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(27, 59, 95)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setText("BOAT NUMBER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 122, 30));

        txtBoatName.setBackground(new java.awt.Color(242, 242, 242));
        txtBoatName.setForeground(new java.awt.Color(102, 102, 102));
        txtBoatName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.add(txtBoatName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 240, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setText("BOAT NAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 122, 30));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel4.setText("CAPACITY");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 140, 30));

        txtDescription.setBackground(new java.awt.Color(242, 242, 242));
        txtDescription.setColumns(20);
        txtDescription.setForeground(new java.awt.Color(102, 102, 102));
        txtDescription.setRows(5);
        txtDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jScrollPane1.setViewportView(txtDescription);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 240, -1));

        spinnerCapacity.setBorder(null);
        jPanel2.add(spinnerCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 240, 30));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel5.setText("DESCRIPTION");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 122, 30));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel3.setText("PRICE/TOUR");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 122, 30));

        txtTourPrice.setBackground(new java.awt.Color(242, 242, 242));
        txtTourPrice.setForeground(new java.awt.Color(102, 102, 102));
        txtTourPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.add(txtTourPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 240, 30));

        rSButtonHover1.setBackground(new java.awt.Color(255, 0, 0));
        rSButtonHover1.setText("CANCEL");
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 110, -1));

        rSButtonHover2.setBackground(new java.awt.Color(0, 204, 0));
        rSButtonHover2.setText("UPDATE");
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 110, -1));

        timePickerButton1.setBackground(new java.awt.Color(27, 59, 95));
        timePickerButton1.setText("Choose Image");
        timePickerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timePickerButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(timePickerButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 260, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel3ComponentAdded(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.add(labelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 220));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 220));

        cmbBoatNumbers.setEditable(false);
        cmbBoatNumbers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double" }));
        cmbBoatNumbers.setSelectedIndex(-1);
        cmbBoatNumbers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBoatNumbersItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbBoatNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 800, 400));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update Boat Details");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 800, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed

    try {
        InputStream is = null;
        PreparedStatement pst = null;
        
        // Get input values
        String boatNumber = (String) cmbBoatNumbers.getSelectedItem();
        String boatName = txtBoatName.getText().trim();
        String description = txtDescription.getText().trim();
        String tourPriceText = txtTourPrice.getText().trim();
        int capacity = (int) spinnerCapacity.getValue();
        
        // Validate required fields
        if (boatNumber == null || boatNumber.isEmpty() ||
                boatName.isEmpty() || description.isEmpty() || 
                tourPriceText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!",
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate tour price
        double tourPrice;
        try {
            tourPrice = Double.parseDouble(tourPriceText);
            if (tourPrice <= 0) {
                JOptionPane.showMessageDialog(this, "Tour price must be a positive number!",
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid tour price format!",
                    "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate capacity
        if (capacity <= 0) {
            JOptionPane.showMessageDialog(this, "Capacity must be greater than 0!",
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirm update
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to update the boat information?",
                "Confirm Update",
                JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Prepare image stream if path exists
        File f = null;
        if (path != null && !path.trim().isEmpty()) {
            f = new File(path);
            if (f.exists()) {
                try {
                    is = new FileInputStream(f);
                } catch (FileNotFoundException ex) {
                    java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
        
        // Prepare SQL query
        String sql;
        if (is != null) {
            sql = "UPDATE boat SET boat_name = ?, boat_image = ?, description = ?, " +
                    "capacity = ?, tour_price = ? WHERE boat_number = ?";
        } else {
            sql = "UPDATE boat SET boat_name = ?, description = ?, " +
                    "capacity = ?, tour_price = ? WHERE boat_number = ?";
        }
        
        // Execute update
        try {
            pst = con.prepareStatement(sql);
            
            if (is != null) {
                pst.setString(1, boatName);
                pst.setBinaryStream(2, is, (int)f.length());
                pst.setString(3, description);
                pst.setInt(4, capacity);
                pst.setDouble(5, tourPrice);
                pst.setString(6, boatNumber);
            } else {
                pst.setString(1, boatName);
                pst.setString(2, description);
                pst.setInt(3, capacity);
                pst.setDouble(4, tourPrice);
                pst.setString(5, boatNumber);
            }
            
            int rowsUpdated = pst.executeUpdate();
            
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Boat updated successfully!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Boat number not found or no changes made.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            // Close resources
            if (is != null) {
                try {
                    is.close();
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
            if (pst != null) {
                try {
                    pst.close();
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }




    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void timePickerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timePickerButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);

        if(load == fileChooser.APPROVE_OPTION){
            f = fileChooser.getSelectedFile();
            path = f.getAbsolutePath();

            ImageIcon ii = new ImageIcon(path);
            Image img = ii.getImage().getScaledInstance(labelImage.getWidth(),
                labelImage.getHeight(),  Image.SCALE_SMOOTH);
            labelImage.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_timePickerButton1ActionPerformed

    private void jPanel3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3ComponentAdded

    private void cmbBoatNumbersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBoatNumbersItemStateChanged
      try {
    // Only proceed if an item is selected and it's not the default empty value
    String selectedBoatNumber = (String) cmbBoatNumbers.getSelectedItem();

    // If no boat number is selected (empty or null), do nothing
    if (selectedBoatNumber == null || selectedBoatNumber.isEmpty() || selectedBoatNumber.equals("Select a Boat Number")) {
        return;
    }

    // Prepare the SQL query to fetch all boat details including image
    String sql = "SELECT boat_name, description, tour_price, capacity, boat_image FROM boat WHERE boat_number = ?";
    pst = con.prepareStatement(sql);
    pst.setString(1, selectedBoatNumber);

    // Execute the query
    rs = pst.executeQuery();

    // Check if the boat exists in the database
    if (rs.next()) {
        // Set the values of the form fields
        txtBoatName.setText(rs.getString("boat_name"));
        txtDescription.setText(rs.getString("description"));
        txtTourPrice.setText(String.format("%.2f", rs.getDouble("tour_price"))); // Format price
        spinnerCapacity.setValue(rs.getInt("capacity"));

        // Load and display the boat image
        loadBoatImage(rs.getBytes("boat_image"));
    } else {
        JOptionPane.showMessageDialog(this, "Boat not found in database", "Error", JOptionPane.WARNING_MESSAGE);
    }
} catch (SQLException ex) {
    java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_cmbBoatNumbersItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminUpdateBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminUpdateBoat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.ComboBoxSuggestion cmbBoatNumbers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImage;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover2;
    private javax.swing.JSpinner spinnerCapacity;
    private com.raven.swing.TimePickerButton timePickerButton1;
    private javax.swing.JTextField txtBoatName;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtTourPrice;
    // End of variables declaration//GEN-END:variables
}
